/**
 * Real-world shaped fixtures. These are the exact spellings produced by curl,
 * yt-dlp, Cookie-Editor and Puppeteer, so the parsers are tested against what
 * they will actually meet rather than an idealised format.
 */

/** Fixed reference time so expiry assertions never drift: 2025-01-01T00:00:00Z. */
export const NOW = 1735689600

/** 2026-01-01T00:00:00Z - comfortably in the future relative to NOW. */
export const FUTURE = 1767225600

/** 2020-01-01T00:00:00Z - expired relative to NOW. */
export const PAST = 1577836800

export const NETSCAPE_BASIC = [
  '# Netscape HTTP Cookie File',
  '# https://curl.se/docs/http-cookies.html',
  '# This file was generated by libcurl! Edit at your own risk.',
  '',
  `.example.com\tTRUE\t/\tFALSE\t${FUTURE}\tsession_id\tabc123`,
  `example.com\tFALSE\t/app\tTRUE\t${FUTURE}\tcsrf\txyz789`,
  '.example.com\tTRUE\t/\tFALSE\t0\ttemp\tvolatile',
].join('\n')

export const NETSCAPE_HTTPONLY = [
  '# Netscape HTTP Cookie File',
  `#HttpOnly_.example.com\tTRUE\t/\tTRUE\t${FUTURE}\tauth_token\tsecret`,
  `.example.com\tTRUE\t/\tFALSE\t${FUTURE}\tvisible\tplain`,
].join('\n')

/** Tabs flattened to spaces, which is what happens when a file is pasted via chat. */
export const NETSCAPE_SPACES = [
  '# Netscape HTTP Cookie File',
  `.example.com TRUE / FALSE ${FUTURE} session_id abc123`,
  `.example.com TRUE / FALSE ${FUTURE} greeting hello world`,
].join('\n')

/** No header comment at all - detection has to rely on the tab layout. */
export const NETSCAPE_NO_HEADER = `.example.com\tTRUE\t/\tFALSE\t${FUTURE}\tonly\tvalue`

export const COOKIE_EDITOR = JSON.stringify(
  [
    {
      domain: '.example.com',
      expirationDate: FUTURE,
      hostOnly: false,
      httpOnly: true,
      name: 'session_id',
      path: '/',
      sameSite: 'no_restriction',
      secure: true,
      session: false,
      storeId: '0',
      value: 'abc123',
    },
    {
      domain: 'example.com',
      hostOnly: true,
      httpOnly: false,
      name: 'temp',
      path: '/app',
      sameSite: 'lax',
      secure: false,
      session: true,
      storeId: '0',
      value: 'volatile',
    },
  ],
  null,
  2,
)

export const PUPPETEER = JSON.stringify(
  [
    {
      name: 'session_id',
      value: 'abc123',
      domain: '.example.com',
      path: '/',
      expires: FUTURE,
      httpOnly: true,
      secure: true,
      sameSite: 'None',
    },
    {
      name: 'temp',
      value: 'volatile',
      domain: 'example.com',
      path: '/',
      expires: -1,
      httpOnly: false,
      secure: false,
      sameSite: 'Lax',
    },
  ],
  null,
  2,
)

export const KEY_VALUE = JSON.stringify(
  { session_id: 'abc123', csrf: 'xyz789' },
  null,
  2,
)

export const HEADER = 'session_id=abc123; csrf=xyz789'

export const HEADER_WITH_PREFIX = 'Cookie: session_id=abc123; csrf=xyz789'

/** A JWT value: contains dots and base64 padding, and must survive untouched. */
export const JWT_VALUE =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.dozjgNryP4J3jVmNHl0w5N_XgL0n3I9PlFUP0THsR8U'
