import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { convert } from '@/lib/cookies'

/**
 * Round-trips cookie files produced by real tools.
 *
 * The fixtures are generated by `curl -c` into the scratchpad directory (see
 * the shell step in the README's verification section). When they are absent -
 * on CI, or on a machine with no network - these cases skip rather than fail,
 * because the unit suite already covers the same code paths against literals.
 */
const DIR =
  process.env.CC_FIXTURE_DIR ??
  '/tmp/claude-1000/-mnt-d-Razrabotka-claudecookie/cd51cc09-3306-4fe6-83c7-32e0151bb216/scratchpad'

function load(name: string): string | null {
  const path = `${DIR}/${name}`
  return existsSync(path) ? readFileSync(path, 'utf8') : null
}

describe('real curl output', () => {
  const simple = load('real.txt')
  const google = load('real2.txt')

  it.skipIf(!simple)('round-trips a plain curl cookie jar', () => {
    const toJson = convert(simple!, { target: 'cookie-editor' })
    expect(toJson.ok).toBe(true)
    expect(toJson.detected).toBe('netscape')

    const back = convert(toJson.output, { target: 'netscape' })
    expect(back.ok).toBe(true)

    // Same cookies, same values, in the same order.
    expect(back.cookies.map((c) => [c.name, c.value, c.domain, c.session])).toEqual(
      convert(simple!, { target: 'netscape' }).cookies.map((c) => [
        c.name,
        c.value,
        c.domain,
        c.session,
      ]),
    )
  })

  it.skipIf(!google)('handles a real Google jar with #HttpOnly_ and long values', () => {
    const result = convert(google!, { target: 'cookie-editor' })
    expect(result.ok).toBe(true)

    const parsed = JSON.parse(result.output) as Array<Record<string, unknown>>
    expect(parsed.length).toBeGreaterThan(0)

    // Every #HttpOnly_ line must have become a real cookie, not a comment.
    expect(parsed.some((c) => c.httpOnly === true)).toBe(true)

    // Values contain - and _ from base64url; none may be truncated or altered.
    for (const cookie of parsed) {
      expect(google!).toContain(String(cookie.value))
    }

    const back = convert(result.output, { target: 'netscape' })
    expect(back.output).toContain('#HttpOnly_')

    // Write the round-tripped file so the shell step can feed it back to curl.
    if (process.env.CC_WRITE_ROUNDTRIP) {
      writeFileSync(`${DIR}/roundtrip.txt`, back.output)
    }
  })

  it.skipIf(!google)('produces Puppeteer output with no session-cookie surprises', () => {
    const result = convert(google!, { target: 'puppeteer' })
    const parsed = JSON.parse(result.output) as Array<{ expires: number; name: string }>

    for (const cookie of parsed) {
      // Either a real future timestamp in seconds, or the -1 sentinel.
      expect(cookie.expires === -1 || cookie.expires > 1_000_000_000).toBe(true)
      expect(cookie.expires).toBeLessThan(1e11)
    }
  })
})
