import type { CookieFormat } from './types'

/**
 * Demo data for the Sample button.
 *
 * Values are obviously fake but structurally realistic: a subdomain cookie, a
 * host-only cookie on a sub-path, an http-only one, and a session cookie - so
 * pressing Sample immediately shows what every field does.
 */

const EXPIRY = 1798761600 // 2027-01-01T00:00:00Z

export const SAMPLE_NETSCAPE = [
  '# Netscape HTTP Cookie File',
  '# https://curl.se/docs/http-cookies.html',
  '# This file was generated by libcurl! Edit at your own risk.',
  '',
  `.example.com\tTRUE\t/\tTRUE\t${EXPIRY}\tsession_id\t8f14e45fceea167a5a36dedd4bea2543`,
  `#HttpOnly_.example.com\tTRUE\t/\tTRUE\t${EXPIRY}\tauth_token\teyJhbGciOiJIUzI1NiJ9.e30.ZRrHA1JJJW8opsbCGfG_HACGpVUMN_a9IV7pAx_Zmeo`,
  `example.com\tFALSE\t/account\tFALSE\t${EXPIRY}\ttheme\tdark`,
  '.example.com\tTRUE\t/\tFALSE\t0\tcart_preview\ttmp-4471',
].join('\n')

export const SAMPLE_COOKIE_EDITOR = JSON.stringify(
  [
    {
      domain: '.example.com',
      expirationDate: EXPIRY,
      hostOnly: false,
      httpOnly: true,
      name: 'session_id',
      path: '/',
      sameSite: 'no_restriction',
      secure: true,
      session: false,
      storeId: '0',
      value: '8f14e45fceea167a5a36dedd4bea2543',
    },
    {
      domain: 'example.com',
      expirationDate: EXPIRY,
      hostOnly: true,
      httpOnly: false,
      name: 'theme',
      path: '/account',
      sameSite: 'lax',
      secure: false,
      session: false,
      storeId: '0',
      value: 'dark',
    },
    {
      domain: '.example.com',
      hostOnly: false,
      httpOnly: false,
      name: 'cart_preview',
      path: '/',
      sameSite: 'unspecified',
      secure: false,
      session: true,
      storeId: '0',
      value: 'tmp-4471',
    },
  ],
  null,
  2,
)

/**
 * Picks the sample that is *not* what the user is currently looking at, so
 * pressing Sample twice demonstrates both directions.
 */
export function sampleFor(detected: CookieFormat | null): string {
  return detected === 'netscape' ? SAMPLE_COOKIE_EDITOR : SAMPLE_NETSCAPE
}

/**
 * Values that exist only in the official Sample payloads above. A real paste
 * that happens to use example.com (the default-domain placeholder) must still
 * be recorded; these two tokens together mean the built-in demo.
 */
const SAMPLE_FINGERPRINT = ['8f14e45fceea167a5a36dedd4bea2543', 'tmp-4471'] as const

export function isSiteSample(text: string): boolean {
  return SAMPLE_FINGERPRINT.every((marker) => text.includes(marker))
}
