#!/usr/bin/env bash
#
# Generates /etc/nginx/conf.d/00-proxy-realip.conf.
#
# The site can sit behind either RTK web protection or Cloudflare, and the two
# get swapped by changing a DNS record. Rather than hand-editing nginx each
# time, both providers are trusted at once: whichever is in front, the visitor's
# address is restored and geolocation keeps working.
#
# Both directives that need the network list - `set_real_ip_from` and the
# `$client_unresolved` guard - are written from the same array here, because if
# they ever drift apart the guard stops protecting the thing it exists for.
#
# Re-run after a provider changes its ranges:
#   bash gen-proxy-trust.sh && nginx -t && systemctl reload nginx

set -euo pipefail

OUT="/etc/nginx/conf.d/00-proxy-realip.conf"

# Networks that are allowed to set the client address via X-Forwarded-For.
# Keep this narrow: anything listed here can claim to be any visitor.
EXTRA_NETS=(
  # RTK web protection filtering nodes, observed in access logs on 2026-09-13.
  # Confirm the full list with RTK and extend if they use more subnets.
  "93.185.164.0/24"
)

nets=("${EXTRA_NETS[@]}")

# Cloudflare publishes its ranges; fetch them so a Cloudflare-fronted setup
# works without any further edits.
cf_ok=1
for url in https://www.cloudflare.com/ips-v4 https://www.cloudflare.com/ips-v6; do
  if ! chunk="$(curl -fsS --max-time 30 "$url")"; then
    cf_ok=0
    continue
  fi
  while read -r cidr; do
    [[ -n "$cidr" ]] && nets+=("$cidr")
  done <<< "$chunk"
done

if [[ $cf_ok -eq 0 ]]; then
  echo "WARNING: could not fetch Cloudflare ranges; only the static list is trusted." >&2
fi

{
  echo "# Generated by gen-proxy-trust.sh on $(date -u +%F). Do not edit by hand."
  echo "# Trusted proxies: RTK web protection + Cloudflare."
  echo
  for cidr in "${nets[@]}"; do
    echo "set_real_ip_from $cidr;"
  done
  echo
  echo "# Both RTK and Cloudflare send the visitor in X-Forwarded-For, so one"
  echo "# header setting covers either provider. Cloudflare additionally sends"
  echo "# CF-Connecting-IP, which 00-geo.conf uses for the country directly."
  echo "real_ip_header X-Forwarded-For;"
  echo "# Walk the chain right-to-left past our own trusted nodes to the first"
  echo "# address we did not put there."
  echo "real_ip_recursive on;"
  echo
  echo "# If \$remote_addr is STILL a proxy address after the rewrite above, the"
  echo "# forwarded header never arrived and we have no idea where the visitor"
  echo "# is. Geolocating the proxy would send the entire world to whichever"
  echo "# country the scrubbing centre sits in, so the redirect is suppressed."
  echo "geo \$client_unresolved {"
  echo "    default     \"\";"
  echo "    127.0.0.0/8 \"local\";"
  for cidr in "${nets[@]}"; do
    echo "    $cidr \"proxy\";"
  done
  echo "}"
  echo
  echo "# Whether the request arrived from one of those proxies, tested on the"
  echo "# address BEFORE realip rewrote it. 00-geo.conf uses this to decide"
  echo "# whether to believe an X-Country-Code or CF-IPCountry header: without"
  echo "# the check, anyone hitting the origin IP directly could pick their own"
  echo "# country by setting a header."
  echo "geo \$realip_remote_addr \$proxy_is_trusted {"
  echo "    default 0;"
  echo "    127.0.0.1 1;"
  echo "    ::1 1;"
  for cidr in "${nets[@]}"; do
    echo "    $cidr 1;"
  done
  echo "}"
  echo
  echo "# Behind a proxy the default log format records the scrubbing node for"
  echo "# every request, which makes the access log useless. This records the"
  echo "# restored client address first and keeps the raw chain in brackets, so"
  echo "# a missing or spoofed header is visible at a glance."
  echo "log_format proxied '\$remote_addr (\$http_x_forwarded_for) - \$remote_user '"
  echo "                   '[\$time_local] \"\$request\" \$status \$body_bytes_sent '"
  echo "                   '\"\$http_referer\" \"\$http_user_agent\"';"
} > "$OUT"

chmod 0644 "$OUT"
echo "wrote $OUT with ${#nets[@]} trusted networks"
