"""Server-side port of lib/cookies — detect, parse, serialize, split, convert.

Keep this aligned with the TypeScript converters and tests/cookies fixtures.
Do not send cookie values to logs.
"""

from __future__ import annotations

import json
import math
import re
from typing import Any

ALL_FORMATS = ("netscape", "cookie-editor", "puppeteer", "key-value", "header")
JSON_FORMATS = ("cookie-editor", "puppeteer", "key-value")
LOSSY_FORMATS = ("key-value", "header")
MAX_INPUT_BYTES = 2 * 1024 * 1024
MAX_SETS = 40
MS_THRESHOLD = 1e11

NETSCAPE_HEADER_RE = re.compile(
    r"^#\s*(Netscape\s+HTTP\s+Cookie\s+File|HTTP\s+Cookie\s+File)",
    re.I | re.M,
)
NETSCAPE_HEADER_LINE = re.compile(
    r"^#\s*(?:Netscape\s+HTTP\s+Cookie\s+File|HTTP\s+Cookie\s+File)",
    re.I,
)
HEADER_PAIR = re.compile(r"^[^=;,\s]+=[^;]*$")
HEADER_LINE = re.compile(
    r"^\s*(?:(?:set-)?cookie\s*:\s*)?[^=;,\s]+=[^;]*(?:;\s*[^=;,\s]+=[^;]*)*$",
    re.I,
)
WS_LINE = re.compile(r"^(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)(?:\s(.*))?$")
GLUED_NETSCAPE = re.compile(
    r"([^\n\t])((?:\.?[A-Za-z0-9][\w.-]*\.[A-Za-z]{2,})\t(?:TRUE|FALSE)\t)",
    re.ASCII,
)

NETSCAPE_FILE_HEADER = (
    "# Netscape HTTP Cookie File\n"
    "# https://curl.se/docs/http-cookies.html\n"
    "# Generated by claudecookie.com — this is a generated file, do not edit by hand.\n"
    "\n"
)

EMPTY_STATS = {
    "total": 0,
    "domains": 0,
    "expired": 0,
    "session": 0,
    "secure": 0,
    "httpOnly": 0,
}


def clean_input(text: str) -> str:
    if text.startswith("\ufeff"):
        text = text[1:]
    return re.sub(r"\r\n?", "\n", text)


def opposite_format(source: str) -> str:
    return "cookie-editor" if source == "netscape" else "netscape"


def is_lossy(fmt: str) -> bool:
    return fmt in LOSSY_FORMATS


def normalize_expires(raw: Any) -> dict[str, Any]:
    if raw is None or raw == "":
        return {"session": True}
    if isinstance(raw, bool):
        return {"session": True}
    if isinstance(raw, (int, float)):
        n = float(raw)
    else:
        try:
            n = float(str(raw).strip())
        except (TypeError, ValueError):
            return {"session": True}
    if not math.isfinite(n):
        return {"session": True}
    if n <= 0:
        return {"session": True}
    seconds = n / 1000 if n >= MS_THRESHOLD else n
    return {"expirationDate": int(round(seconds)), "session": False}


def normalize_same_site(raw: Any) -> str:
    if not isinstance(raw, str):
        return "unspecified"
    key = raw.strip().lower()
    if key in ("none", "no_restriction", "norestriction"):
        return "no_restriction"
    if key == "lax":
        return "lax"
    if key == "strict":
        return "strict"
    return "unspecified"


def to_puppeteer_same_site(value: str) -> str | None:
    if value == "no_restriction":
        return "None"
    if value == "lax":
        return "Lax"
    if value == "strict":
        return "Strict"
    return None


def normalize_domain(domain: Any, include_subdomains: bool | None = None) -> str:
    d = domain.strip() if isinstance(domain, str) else ""
    if not d:
        return ""
    d = re.sub(r"^https?://", "", d, flags=re.I)
    d = re.sub(r"/.*$", "", d)
    d = re.sub(r":\d+$", "", d)
    d = d.lower()
    if include_subdomains is True and not d.startswith("."):
        d = f".{d}"
    if include_subdomains is False and d.startswith("."):
        d = d[1:]
    return d


def is_host_only(domain: str) -> bool:
    return bool(domain) and not domain.startswith(".")


def make_cookie(inp: dict[str, Any]) -> dict[str, Any]:
    domain = inp.get("domain") or ""
    expiry = normalize_expires(inp.get("expires"))
    session = True if inp.get("session") is True else bool(expiry.get("session"))
    cookie: dict[str, Any] = {
        "name": inp["name"],
        "value": inp["value"],
        "domain": domain,
        "path": inp["path"].strip() if isinstance(inp.get("path"), str) and inp["path"].strip() else "/",
        "secure": bool(inp.get("secure")),
        "httpOnly": bool(inp.get("httpOnly")),
        "hostOnly": inp["hostOnly"] if isinstance(inp.get("hostOnly"), bool) else is_host_only(domain),
        "session": session,
        "sameSite": inp.get("sameSite") or "unspecified",
    }
    if not session and "expirationDate" in expiry:
        cookie["expirationDate"] = expiry["expirationDate"]
    return cookie


def is_expired(cookie: dict[str, Any], now: int) -> bool:
    exp = cookie.get("expirationDate")
    return (not cookie.get("session")) and exp is not None and exp < now


def compute_stats(cookies: list[dict[str, Any]], now: int) -> dict[str, int]:
    domains: set[str] = set()
    expired = session = secure = http_only = 0
    for cookie in cookies:
        domain = cookie.get("domain") or ""
        if domain:
            domains.add(domain.lstrip("."))
        if is_expired(cookie, now):
            expired += 1
        if cookie.get("session"):
            session += 1
        if cookie.get("secure"):
            secure += 1
        if cookie.get("httpOnly"):
            http_only += 1
    return {
        "total": len(cookies),
        "domains": len(domains),
        "expired": expired,
        "session": session,
        "secure": secure,
        "httpOnly": http_only,
    }


def _is_record(value: Any) -> bool:
    return isinstance(value, dict)


def _is_primitive_strict(value: Any) -> bool:
    return isinstance(value, str) or (isinstance(value, (int, float)) and not isinstance(value, bool)) or isinstance(value, bool)


def _is_bool_field(value: str | None) -> bool:
    return value in ("TRUE", "FALSE", "true", "false")


def classify_json(parsed: Any) -> dict[str, Any] | None:
    if isinstance(parsed, list):
        return _classify_cookie_array(parsed)
    if _is_record(parsed):
        wrapped = parsed.get("cookies", parsed.get("Cookies"))
        if isinstance(wrapped, list):
            return _classify_cookie_array(wrapped)
        if isinstance(parsed.get("name"), str) and "value" in parsed:
            return _classify_cookie_array([parsed])
        entries = list(parsed.items())
        if entries and all(_is_primitive_strict(v) for _, v in entries):
            return {"format": "key-value", "confidence": 0.9}
    return None


def _classify_cookie_array(items: list[Any]) -> dict[str, Any] | None:
    first = next((item for item in items if _is_record(item)), None)
    if first is None:
        return {"format": "cookie-editor", "confidence": 0.4} if len(items) == 0 else None
    if "name" not in first:
        return None
    if "expirationDate" in first or "storeId" in first or "hostOnly" in first:
        return {"format": "cookie-editor", "confidence": 1}
    if "expires" in first:
        return {"format": "puppeteer", "confidence": 0.95}
    same = first.get("sameSite")
    if isinstance(same, str) and re.match(r"^(None|Lax|Strict)$", same):
        return {"format": "puppeteer", "confidence": 0.9}
    return {"format": "puppeteer", "confidence": 0.6}


def detect_json(text: str) -> dict[str, Any] | None:
    try:
        parsed = json.loads(text)
    except (TypeError, ValueError):
        return None
    return classify_json(parsed)


def detect_netscape(text: str) -> dict[str, Any] | None:
    if NETSCAPE_HEADER_RE.search(text):
        return {"format": "netscape", "confidence": 1}
    tab_delimited = 0
    whitespace_delimited = 0
    for line in text.split("\n"):
        trimmed = line.strip()
        if not trimmed or (trimmed.startswith("#") and not trimmed.startswith("#HttpOnly_")):
            continue
        body = re.sub(r"^#HttpOnly_", "", trimmed)
        if len(body.split("\t")) >= 7:
            tab_delimited += 1
            continue
        fields = re.split(r"\s+", body)
        if len(fields) >= 7 and _is_bool_field(fields[1]) and _is_bool_field(fields[3]):
            whitespace_delimited += 1
    if tab_delimited > 0:
        return {"format": "netscape", "confidence": 0.95}
    if whitespace_delimited > 0:
        return {"format": "netscape", "confidence": 0.75}
    return None


def detect_header(text: str) -> dict[str, Any] | None:
    body = re.sub(r"^\s*(set-)?cookie\s*:\s*", "", text, flags=re.I).strip()
    if not body:
        return None
    pairs = [p.strip() for p in body.split(";") if p.strip()]
    if not pairs or not all(HEADER_PAIR.match(p) for p in pairs):
        return None
    return {"format": "header", "confidence": 0.85 if len(pairs) > 1 else 0.6}


def detect_format(raw: str) -> dict[str, Any]:
    text = clean_input(raw).strip()
    if not text:
        return {"format": None, "confidence": 0}
    if text.startswith("[") or text.startswith("{"):
        from_json = detect_json(text)
        if from_json:
            return from_json
    netscape = detect_netscape(text)
    if netscape:
        return netscape
    header = detect_header(text)
    if header:
        return header
    return {"format": None, "confidence": 0}


def _pick(obj: dict[str, Any], *keys: str) -> Any:
    for key in keys:
        if obj.get(key) is not None:
            return obj[key]
    return None


def _stringify(value: Any) -> str:
    if isinstance(value, str):
        return value
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    dumped = json.dumps(value, ensure_ascii=False)
    return dumped if dumped is not None else ""


def _as_string(value: Any) -> str | None:
    return value if isinstance(value, str) and value.strip() else None


def _as_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return bool(re.match(r"^(true|1|yes)$", value.strip(), re.I))
    return False


def _as_bool_or_undefined(value: Any) -> bool | None:
    return None if value is None else _as_bool(value)


def _json_error_line(raw: str, err: BaseException) -> int | None:
    pos = getattr(err, "pos", None)
    if isinstance(pos, int):
        return raw[:pos].count("\n") + 1
    message = str(err)
    match = re.search(r"position\s+(\d+)", message, re.I)
    if not match:
        return None
    offset = int(match.group(1))
    return raw[:offset].count("\n") + 1


def _unwrap_json(parsed: Any) -> list[Any] | dict[str, Any] | None:
    if isinstance(parsed, list):
        return parsed
    if _is_record(parsed):
        wrapped = parsed.get("cookies", parsed.get("Cookies"))
        if isinstance(wrapped, list):
            return wrapped
        if isinstance(parsed.get("name"), str) and "value" in parsed:
            return [parsed]
        entries = list(parsed.items())
        if entries and all(_is_primitive_strict(v) for _, v in entries):
            return parsed
        if not entries:
            return []
    return None


def parse_json(raw: str, default_domain: str | None = None) -> dict[str, Any]:
    issues: list[dict[str, Any]] = []
    try:
        parsed = json.loads(raw)
    except (TypeError, ValueError) as err:
        issue: dict[str, Any] = {"level": "error", "message": "issue.json.invalid"}
        line = _json_error_line(raw, err)
        if line is not None:
            issue["line"] = line
        return {"cookies": [], "issues": [issue]}

    items = _unwrap_json(parsed)
    if items is None:
        return {"cookies": [], "issues": [{"level": "error", "message": "issue.json.unsupportedShape"}]}

    if not isinstance(items, list):
        cookies = []
        for name, value in items.items():
            cookies.append(
                make_cookie(
                    {
                        "name": name,
                        "value": _stringify(value),
                        "domain": normalize_domain(default_domain),
                        "path": "/",
                        "session": True,
                    }
                )
            )
        if not cookies:
            issues.append({"level": "error", "message": "issue.json.empty"})
        return {"cookies": cookies, "issues": issues}

    cookies = []
    for index, item in enumerate(items):
        if not _is_record(item):
            issues.append({"level": "error", "message": "issue.json.notAnObject", "line": index + 1})
            continue
        name = _pick(item, "name", "Name", "key")
        if not isinstance(name, str) or not name:
            issues.append({"level": "error", "message": "issue.json.missingName", "line": index + 1})
            continue
        raw_value = _pick(item, "value", "Value")
        if raw_value is None:
            issues.append({"level": "error", "message": "issue.json.missingValue", "line": index + 1})
            continue
        host_only_raw = _pick(item, "hostOnly", "hostonly")
        domain_raw = _pick(item, "domain", "Domain")
        domain = normalize_domain(
            domain_raw if domain_raw is not None else default_domain,
            (not host_only_raw) if isinstance(host_only_raw, bool) else None,
        )
        cookies.append(
            make_cookie(
                {
                    "name": name,
                    "value": _stringify(raw_value),
                    "domain": domain,
                    "path": _as_string(_pick(item, "path", "Path")) or "/",
                    "secure": _as_bool(_pick(item, "secure", "Secure")),
                    "httpOnly": _as_bool(_pick(item, "httpOnly", "httponly", "HttpOnly", "http_only")),
                    "hostOnly": host_only_raw if isinstance(host_only_raw, bool) else None,
                    "sameSite": normalize_same_site(_pick(item, "sameSite", "samesite", "SameSite")),
                    "expires": _pick(item, "expirationDate", "expires", "expiry", "expiration_date", "Expires"),
                    "session": _as_bool_or_undefined(_pick(item, "session", "Session")),
                }
            )
        )
    if not cookies and not any(i.get("level") == "error" for i in issues):
        issues.append({"level": "error", "message": "issue.json.empty"})
    return {"cookies": cookies, "issues": issues}


def parse_netscape(raw: str) -> dict[str, Any]:
    issues: list[dict[str, Any]] = []
    cookies: list[dict[str, Any]] = []
    saw_ws = False
    for index, line in enumerate(clean_input(raw).split("\n")):
        line_no = index + 1
        trimmed = line.strip()
        if not trimmed:
            continue
        http_only = False
        body = trimmed
        if re.match(r"^#HttpOnly_", body, re.I):
            http_only = True
            body = re.sub(r"^#HttpOnly_", "", body, flags=re.I)
        elif body.startswith("#"):
            continue
        fields = body.split("\t")
        if len(fields) >= 7:
            fields = [*fields[:6], "\t".join(fields[6:])]
        elif len(fields) == 6:
            fields = [*fields, ""]
            issues.append({"level": "warning", "line": line_no, "message": "issue.netscape.emptyValue"})
        else:
            match = WS_LINE.match(body)
            if not match:
                issues.append({"level": "error", "line": line_no, "message": "issue.netscape.badLine"})
                continue
            fields = [match.group(i) or "" for i in range(1, 8)]
            saw_ws = True
        domain_raw, include_sub, path, secure, expires, name, value = fields[:7]
        if not name:
            issues.append({"level": "error", "line": line_no, "message": "issue.netscape.missingName"})
            continue
        flag_says_include = bool(re.match(r"^true$", include_sub, re.I))
        dot_says_include = domain_raw.startswith(".")
        domain = f".{domain_raw.lstrip('.')}" if (dot_says_include or flag_says_include) else domain_raw
        cookies.append(
            make_cookie(
                {
                    "name": name,
                    "value": value,
                    "domain": domain.lower(),
                    "path": path,
                    "secure": bool(re.match(r"^true$", secure, re.I)),
                    "httpOnly": http_only,
                    "expires": expires,
                }
            )
        )
    if saw_ws:
        issues.append({"level": "warning", "message": "issue.netscape.spacesNotTabs"})
    if not cookies and not any(i.get("level") == "error" for i in issues):
        issues.append({"level": "error", "message": "issue.netscape.noCookies"})
    return {"cookies": cookies, "issues": issues}


def parse_header(raw: str, default_domain: str | None = None) -> dict[str, Any]:
    issues: list[dict[str, Any]] = []
    cookies: list[dict[str, Any]] = []
    body = re.sub(r"^\s*(set-)?cookie\s*:\s*", "", clean_input(raw), flags=re.I).strip()
    if not body:
        return {"cookies": cookies, "issues": [{"level": "error", "message": "issue.header.empty"}]}
    domain = normalize_domain(default_domain)
    for pair in body.split(";"):
        chunk = pair.strip()
        if not chunk:
            continue
        eq = chunk.find("=")
        if eq <= 0:
            issues.append({"level": "warning", "message": "issue.header.badPair"})
            continue
        name = chunk[:eq].strip()
        value = chunk[eq + 1 :].strip()
        if not name:
            issues.append({"level": "warning", "message": "issue.header.badPair"})
            continue
        cookies.append(make_cookie({"name": name, "value": value, "domain": domain, "path": "/", "session": True}))
    if not cookies and not any(i.get("level") == "error" for i in issues):
        issues.append({"level": "error", "message": "issue.header.empty"})
    return {"cookies": cookies, "issues": issues}


def serialize_netscape(cookies: list[dict[str, Any]], include_header: bool = True) -> str:
    lines = []
    for cookie in cookies:
        include_sub = "TRUE" if str(cookie.get("domain") or "").startswith(".") else "FALSE"
        expires = 0 if cookie.get("session") else int(round(cookie.get("expirationDate") or 0))
        domain = cookie.get("domain") or ""
        if cookie.get("httpOnly"):
            domain = f"#HttpOnly_{domain}"
        lines.append(
            "\t".join(
                [
                    domain,
                    include_sub,
                    cookie.get("path") or "/",
                    "TRUE" if cookie.get("secure") else "FALSE",
                    str(expires),
                    cookie.get("name") or "",
                    cookie.get("value") or "",
                ]
            )
        )
    body = "\n".join(lines)
    return f"{NETSCAPE_FILE_HEADER}{body}\n" if include_header else f"{body}\n"


def _json_dump(obj: Any) -> str:
    return json.dumps(obj, indent=2, ensure_ascii=False) + "\n"


def serialize_cookie_editor(cookies: list[dict[str, Any]]) -> str:
    out = []
    for cookie in cookies:
        item: dict[str, Any] = {"domain": cookie.get("domain") or ""}
        if not cookie.get("session") and cookie.get("expirationDate") is not None:
            item["expirationDate"] = cookie["expirationDate"]
        item["hostOnly"] = bool(cookie.get("hostOnly"))
        item["httpOnly"] = bool(cookie.get("httpOnly"))
        item["name"] = cookie.get("name") or ""
        item["path"] = cookie.get("path") or "/"
        item["sameSite"] = cookie.get("sameSite") or "unspecified"
        item["secure"] = bool(cookie.get("secure"))
        item["session"] = bool(cookie.get("session"))
        item["storeId"] = "0"
        item["value"] = cookie.get("value") or ""
        out.append(item)
    return _json_dump(out)


def serialize_puppeteer(cookies: list[dict[str, Any]]) -> str:
    out = []
    for cookie in cookies:
        same = to_puppeteer_same_site(cookie.get("sameSite") or "unspecified")
        item: dict[str, Any] = {
            "name": cookie.get("name") or "",
            "value": cookie.get("value") or "",
            "domain": cookie.get("domain") or "",
            "path": cookie.get("path") or "/",
            "expires": -1 if cookie.get("session") else (cookie.get("expirationDate") if cookie.get("expirationDate") is not None else -1),
            "httpOnly": bool(cookie.get("httpOnly")),
            "secure": bool(cookie.get("secure")),
        }
        if same:
            item["sameSite"] = same
        out.append(item)
    return _json_dump(out)


def serialize_key_value(cookies: list[dict[str, Any]]) -> str:
    out: dict[str, str] = {}
    for cookie in cookies:
        out[cookie.get("name") or ""] = cookie.get("value") or ""
    return _json_dump(out)


def serialize_header(cookies: list[dict[str, Any]]) -> str:
    return "; ".join(f"{c.get('name') or ''}={c.get('value') or ''}" for c in cookies)


def serialize(fmt: str, cookies: list[dict[str, Any]]) -> str:
    if fmt == "netscape":
        return serialize_netscape(cookies)
    if fmt == "cookie-editor":
        return serialize_cookie_editor(cookies)
    if fmt == "puppeteer":
        return serialize_puppeteer(cookies)
    if fmt == "key-value":
        return serialize_key_value(cookies)
    if fmt == "header":
        return serialize_header(cookies)
    raise ValueError(fmt)


def _run_parser(fmt: str, text: str, default_domain: str | None) -> dict[str, Any]:
    if fmt == "netscape":
        return parse_netscape(text)
    if fmt == "header":
        return parse_header(text, default_domain)
    return parse_json(text, default_domain)


def _dedupe(parsed: dict[str, Any]) -> dict[str, Any]:
    cookies = parsed["cookies"]
    issues = list(parsed["issues"])
    by_key: dict[str, dict[str, Any]] = {}
    for cookie in cookies:
        by_key[f"{cookie.get('name')} {cookie.get('domain')} {cookie.get('path')}"] = cookie
    if len(by_key) == len(cookies):
        return {"cookies": cookies, "issues": issues}
    return {
        "cookies": list(by_key.values()),
        "issues": [*issues, {"level": "warning", "message": "issue.duplicates"}],
    }


def _loss_warnings(cookies: list[dict[str, Any]], source: str, target: str) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    if target == "netscape" and any(not c.get("domain") for c in cookies):
        out.append({"level": "warning", "message": "issue.missingDomain"})
    if is_lossy(target) and not is_lossy(source):
        carries_more = any(
            (not c.get("session")) or c.get("path") != "/" or c.get("secure") or c.get("httpOnly")
            for c in cookies
        )
        if carries_more:
            out.append({"level": "warning", "message": "issue.lossyTarget"})
    if target == "key-value":
        names = [c.get("name") for c in cookies]
        if len(set(names)) != len(cookies):
            out.append({"level": "warning", "message": "issue.nameCollision"})
    return out


def _fail(target: str, issues: list[dict[str, Any]], detected: str | None = None) -> dict[str, Any]:
    return {
        "ok": False,
        "detected": detected,
        "target": target,
        "output": "",
        "cookies": [],
        "issues": issues,
        "stats": dict(EMPTY_STATS),
    }


def convert(
    raw: str,
    *,
    source: str | None = None,
    target: str | None = None,
    default_domain: str | None = None,
    now: int | None = None,
) -> dict[str, Any]:
    import time

    stamp = int(now if now is not None else time.time())
    text = clean_input(raw)
    chosen_target = target or "cookie-editor"
    if not text.strip():
        return _fail(chosen_target, [])
    if len(text.encode("utf-8")) > MAX_INPUT_BYTES:
        return _fail(chosen_target, [{"level": "error", "message": "issue.tooLarge"}])
    detected = source or detect_format(text)["format"]
    chosen_target = target or (opposite_format(detected) if detected else "cookie-editor")
    if not detected:
        return _fail(chosen_target, [{"level": "error", "message": "issue.unknownFormat"}])
    parsed = _dedupe(_run_parser(detected, text, default_domain))
    cookies = parsed["cookies"]
    issues = list(parsed["issues"])
    if not cookies:
        return {
            "ok": False,
            "detected": detected,
            "target": chosen_target,
            "output": "",
            "cookies": [],
            "issues": issues,
            "stats": dict(EMPTY_STATS),
        }
    issues.extend(_loss_warnings(cookies, detected, chosen_target))
    return {
        "ok": True,
        "detected": detected,
        "target": chosen_target,
        "output": serialize(chosen_target, cookies),
        "cookies": cookies,
        "issues": issues,
        "stats": compute_stats(cookies, stamp),
    }


def _has_cookie_line(block: str) -> bool:
    for line in block.split("\n"):
        trimmed = line.strip()
        if not trimmed:
            continue
        if trimmed.startswith("#HttpOnly_"):
            return True
        if not trimmed.startswith("#"):
            return True
    return False


def _is_real_set(block: str) -> bool:
    return _has_cookie_line(block) and detect_format(block)["format"] is not None


def _netscape_name(line: str) -> str | None:
    body = re.sub(r"^#HttpOnly_", "", line)
    tabs = body.split("\t")
    if len(tabs) >= 7:
        name = (tabs[5] or "").strip()
        return name or None
    parts = re.split(r"\s+", body)
    if len(parts) >= 7 and _is_bool_field(parts[1]) and _is_bool_field(parts[3]):
        name = (parts[5] or "").strip()
        return name or None
    return None


def _split_netscape_by_name(text: str) -> list[str]:
    groups: list[str] = []
    cur: list[str] = []
    seen: set[str] = set()

    def flush() -> None:
        nonlocal cur, seen
        if seen:
            groups.append("\n".join(cur).strip())
            cur = []
            seen = set()

    for line in text.split("\n"):
        trimmed = line.strip()
        if not trimmed:
            if cur:
                cur.append(line)
            continue
        if NETSCAPE_HEADER_LINE.match(trimmed):
            flush()
            cur.append(line)
            continue
        if trimmed.startswith("#"):
            if cur:
                cur.append(line)
            continue
        name = _netscape_name(trimmed)
        if name and name in seen:
            flush()
        if name:
            seen.add(name)
        cur.append(line)
    if cur and any(item.strip() for item in cur):
        groups.append("\n".join(cur).strip())
    return [g for g in groups if g]


def _scan_top_level_json(text: str) -> list[str]:
    out: list[str] = []
    depth = 0
    start = -1
    in_string = False
    escaped = False
    for i, ch in enumerate(text):
        if in_string:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == '"':
                in_string = False
            continue
        if ch == '"':
            in_string = True
            if start == -1:
                start = i
            continue
        if ch in "{[":
            if depth == 0:
                start = i
            depth += 1
        elif ch in "}]":
            depth -= 1
            if depth == 0 and start != -1:
                out.append(text[start : i + 1].strip())
                start = -1
            elif depth < 0:
                return []
        elif depth == 0 and start != -1 and ch not in " \t\n\r":
            return []
    return out if depth == 0 and not in_string else []


def _remainders_after_json(text: str, values: list[str]) -> list[str]:
    ranges: list[tuple[int, int]] = []
    from_idx = 0
    for value in values:
        i = text.find(value, from_idx)
        if i == -1:
            continue
        ranges.append((i, i + len(value)))
        from_idx = i + len(value)
    rest = ""
    cursor = 0
    for start, end in ranges:
        rest += text[cursor:start]
        cursor = end
    rest += text[cursor:]
    return [b.strip() for b in re.split(r"\n[ \t]*\n+", rest) if _has_cookie_line(b.strip())]


def _cap(sets: list[str]) -> list[str]:
    return sets[:MAX_SETS]


def split_cookie_sets(raw: str) -> list[str]:
    text = clean_input(raw).strip()
    if not text:
        return []
    json_values = _scan_top_level_json(text)
    if len(json_values) > 1:
        whole = detect_format(text)["format"]
        take_json = text[0] in "[{" or (whole != "netscape" and all(_is_real_set(v) for v in json_values))
        if take_json:
            extra = [b for b in _remainders_after_json(text, json_values) if _is_real_set(b)]
            return _cap([*json_values, *extra])
    blocks = [b.strip() for b in re.split(r"\n[ \t]*\n+", text) if _has_cookie_line(b.strip())]
    if len(blocks) > 1 and all(_is_real_set(b) for b in blocks):
        return _cap(blocks)
    if detect_format(text)["format"] == "netscape":
        by_name = _split_netscape_by_name(GLUED_NETSCAPE.sub(r"\1\n\2", text))
        if len(by_name) > 1:
            return _cap(by_name)
    lines = [l.strip() for l in text.split("\n") if l.strip() and not l.strip().startswith("#")]
    if len(lines) > 1 and all(HEADER_LINE.match(l) for l in lines):
        return _cap(lines)
    return [text]


def join_cookie_sets(parts: list[str]) -> str:
    cleaned = [p.strip() for p in parts if p and p.strip()][:MAX_SETS]
    return "\n\n".join(cleaned)


def convert_batch(raw: str, **opts: Any) -> list[dict[str, Any]]:
    sets = split_cookie_sets(raw)
    if not sets:
        return [convert("", **opts)]
    return [convert(item, **opts) for item in sets]


def convert_combined(raw: str, **opts: Any) -> dict[str, Any]:
    import time

    stamp = int(opts.get("now") if opts.get("now") is not None else time.time())
    results = [r for r in convert_batch(raw, **opts) if r.get("ok")]
    if not results:
        sets = split_cookie_sets(raw)
        return convert(sets[0] if sets else "", **opts)
    first = results[0]
    detected = first.get("detected")
    target = opts.get("target") or first.get("target")
    merged = _dedupe({"cookies": [c for r in results for c in r["cookies"]], "issues": []})
    issues = list(merged["issues"])
    issues.extend(_loss_warnings(merged["cookies"], detected or target, target))
    return {
        "ok": len(merged["cookies"]) > 0,
        "detected": detected,
        "target": target,
        "output": serialize(target, merged["cookies"]),
        "cookies": merged["cookies"],
        "issues": issues,
        "stats": compute_stats(merged["cookies"], stamp),
    }
