#!/usr/bin/env python3
"""Port of tests/cookies — same fixtures, same convert contract."""

import json
import unittest

from cookie_convert import (
    ALL_FORMATS,
    MAX_INPUT_BYTES,
    MAX_SETS,
    convert,
    convert_batch,
    convert_combined,
    detect_format,
    join_cookie_sets,
    normalize_expires,
    normalize_same_site,
    opposite_format,
    parse_header,
    parse_json,
    parse_netscape,
    split_cookie_sets,
)

NOW = 1735689600
FUTURE = 1767225600
PAST = 1577836800

NETSCAPE_BASIC = "\n".join(
    [
        "# Netscape HTTP Cookie File",
        "# https://curl.se/docs/http-cookies.html",
        "# This file was generated by libcurl! Edit at your own risk.",
        "",
        f".example.com\tTRUE\t/\tFALSE\t{FUTURE}\tsession_id\tabc123",
        f"example.com\tFALSE\t/app\tTRUE\t{FUTURE}\tcsrf\txyz789",
        ".example.com\tTRUE\t/\tFALSE\t0\ttemp\tvolatile",
    ]
)

NETSCAPE_HTTPONLY = "\n".join(
    [
        "# Netscape HTTP Cookie File",
        f"#HttpOnly_.example.com\tTRUE\t/\tTRUE\t{FUTURE}\tauth_token\tsecret",
        f".example.com\tTRUE\t/\tFALSE\t{FUTURE}\tvisible\tplain",
    ]
)

NETSCAPE_SPACES = "\n".join(
    [
        "# Netscape HTTP Cookie File",
        f".example.com TRUE / FALSE {FUTURE} session_id abc123",
        f".example.com TRUE / FALSE {FUTURE} greeting hello world",
    ]
)

NETSCAPE_NO_HEADER = f".example.com\tTRUE\t/\tFALSE\t{FUTURE}\tonly\tvalue"

COOKIE_EDITOR = json.dumps(
    [
        {
            "domain": ".example.com",
            "expirationDate": FUTURE,
            "hostOnly": False,
            "httpOnly": True,
            "name": "session_id",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": True,
            "session": False,
            "storeId": "0",
            "value": "abc123",
        },
        {
            "domain": "example.com",
            "hostOnly": True,
            "httpOnly": False,
            "name": "temp",
            "path": "/app",
            "sameSite": "lax",
            "secure": False,
            "session": True,
            "storeId": "0",
            "value": "volatile",
        },
    ],
    indent=2,
)

PUPPETEER = json.dumps(
    [
        {
            "name": "session_id",
            "value": "abc123",
            "domain": ".example.com",
            "path": "/",
            "expires": FUTURE,
            "httpOnly": True,
            "secure": True,
            "sameSite": "None",
        },
        {
            "name": "temp",
            "value": "volatile",
            "domain": "example.com",
            "path": "/",
            "expires": -1,
            "httpOnly": False,
            "secure": False,
            "sameSite": "Lax",
        },
    ],
    indent=2,
)

KEY_VALUE = json.dumps({"session_id": "abc123", "csrf": "xyz789"}, indent=2)
HEADER = "session_id=abc123; csrf=xyz789"
HEADER_WITH_PREFIX = "Cookie: session_id=abc123; csrf=xyz789"
JWT_VALUE = (
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0."
    "dozjgNryP4J3jVmNHl0w5N_XgL0n3I9PlFUP0THsR8U"
)

OPTS = {"now": NOW}


class DetectTests(unittest.TestCase):
    def test_netscape_header(self):
        self.assertEqual(detect_format(NETSCAPE_BASIC), {"format": "netscape", "confidence": 1})

    def test_netscape_no_header(self):
        result = detect_format(NETSCAPE_NO_HEADER)
        self.assertEqual(result["format"], "netscape")
        self.assertGreater(result["confidence"], 0.9)

    def test_netscape_spaces(self):
        self.assertEqual(detect_format(NETSCAPE_SPACES)["format"], "netscape")

    def test_httponly_prefix(self):
        self.assertEqual(detect_format(NETSCAPE_HTTPONLY)["format"], "netscape")

    def test_json_dialects(self):
        self.assertEqual(detect_format(COOKIE_EDITOR), {"format": "cookie-editor", "confidence": 1})
        self.assertEqual(detect_format(PUPPETEER)["format"], "puppeteer")
        self.assertEqual(detect_format(KEY_VALUE)["format"], "key-value")

    def test_header(self):
        self.assertEqual(detect_format(HEADER)["format"], "header")
        self.assertEqual(detect_format(HEADER_WITH_PREFIX)["format"], "header")

    def test_wrapped_and_single(self):
        wrapped = json.dumps({"cookies": json.loads(COOKIE_EDITOR)})
        self.assertEqual(detect_format(wrapped)["format"], "cookie-editor")
        single = json.dumps(json.loads(COOKIE_EDITOR)[0])
        self.assertEqual(detect_format(single)["format"], "cookie-editor")

    def test_bom_and_crlf(self):
        self.assertEqual(detect_format("\ufeff" + COOKIE_EDITOR)["format"], "cookie-editor")
        self.assertEqual(detect_format(NETSCAPE_BASIC.replace("\n", "\r\n"))["format"], "netscape")

    def test_garbage(self):
        self.assertIsNone(detect_format("")["format"])
        self.assertIsNone(detect_format("   \n\t ")["format"])
        self.assertIsNone(detect_format("the quick brown fox jumped")["format"])
        self.assertIsNone(detect_format('[{"name": "a", ')["format"])

    def test_opposite(self):
        self.assertEqual(opposite_format("netscape"), "cookie-editor")
        self.assertEqual(opposite_format("cookie-editor"), "netscape")
        self.assertEqual(opposite_format("header"), "netscape")


class NormalizeTests(unittest.TestCase):
    def test_expires_session_spellings(self):
        for raw in (None, "", 0, "0", -1, "-1"):
            self.assertEqual(normalize_expires(raw), {"session": True}, raw)

    def test_expires_seconds_and_ms(self):
        self.assertEqual(normalize_expires(FUTURE), {"expirationDate": FUTURE, "session": False})
        self.assertEqual(normalize_expires(FUTURE * 1000), {"expirationDate": FUTURE, "session": False})
        self.assertEqual(
            normalize_expires(FUTURE + 0.7382),
            {"expirationDate": FUTURE + 1, "session": False},
        )
        self.assertEqual(normalize_expires("not-a-date"), {"session": True})

    def test_same_site(self):
        self.assertEqual(normalize_same_site("None"), "no_restriction")
        self.assertEqual(normalize_same_site("no_restriction"), "no_restriction")
        self.assertEqual(normalize_same_site("Lax"), "lax")
        self.assertEqual(normalize_same_site("strict"), "strict")
        self.assertEqual(normalize_same_site(None), "unspecified")
        self.assertEqual(normalize_same_site("nonsense"), "unspecified")


class ParseTests(unittest.TestCase):
    def test_netscape_fields(self):
        cookies = parse_netscape(NETSCAPE_BASIC)["cookies"]
        self.assertEqual(len(cookies), 3)
        self.assertEqual(cookies[0]["name"], "session_id")
        self.assertEqual(cookies[0]["domain"], ".example.com")
        self.assertFalse(cookies[0]["secure"])
        self.assertFalse(cookies[0]["hostOnly"])
        self.assertEqual(cookies[0]["expirationDate"], FUTURE)
        self.assertEqual(cookies[1]["name"], "csrf")
        self.assertEqual(cookies[1]["path"], "/app")
        self.assertTrue(cookies[1]["secure"])
        self.assertTrue(cookies[1]["hostOnly"])

    def test_httponly_and_spaces(self):
        cookies = parse_netscape(NETSCAPE_HTTPONLY)["cookies"]
        self.assertTrue(cookies[0]["httpOnly"])
        self.assertFalse(cookies[1]["httpOnly"])
        spaced = parse_netscape(NETSCAPE_SPACES)
        self.assertEqual(len(spaced["cookies"]), 2)
        self.assertTrue(any(i["message"] == "issue.netscape.spacesNotTabs" for i in spaced["issues"]))

    def test_json_and_header(self):
        self.assertEqual(len(parse_json(COOKIE_EDITOR)["cookies"]), 2)
        self.assertEqual(len(parse_json(PUPPETEER)["cookies"]), 2)
        self.assertEqual(len(parse_json(KEY_VALUE)["cookies"]), 2)
        header = parse_header(HEADER_WITH_PREFIX)
        self.assertEqual([c["name"] for c in header["cookies"]], ["session_id", "csrf"])


class ConvertTests(unittest.TestCase):
    def test_auto_direction(self):
        r = convert(NETSCAPE_BASIC, **OPTS)
        self.assertTrue(r["ok"])
        self.assertEqual(r["detected"], "netscape")
        self.assertEqual(r["target"], "cookie-editor")
        self.assertEqual(len(json.loads(r["output"])), 3)
        for raw in (COOKIE_EDITOR, PUPPETEER, KEY_VALUE, HEADER):
            out = convert(raw, **OPTS)
            self.assertTrue(out["ok"], raw[:30])
            self.assertEqual(out["target"], "netscape")
            self.assertIn("# Netscape HTTP Cookie File", out["output"])

    def test_explicit_target_and_source(self):
        r = convert(NETSCAPE_BASIC, target="puppeteer", **OPTS)
        self.assertEqual(r["target"], "puppeteer")
        self.assertIn("expires", json.loads(r["output"])[0])
        r = convert(HEADER, source="header", default_domain="example.com", **OPTS)
        self.assertEqual(r["detected"], "header")

    def test_round_trips(self):
        json_out = convert(NETSCAPE_BASIC, **OPTS)["output"]
        back = convert(json_out, target="netscape", **OPTS)["output"]
        self.assertEqual(back, convert(NETSCAPE_BASIC, target="netscape", **OPTS)["output"])
        puppeteer = convert(NETSCAPE_BASIC, target="puppeteer", **OPTS)["output"]
        back = convert(puppeteer, target="netscape", **OPTS)["output"]
        self.assertEqual(back, convert(NETSCAPE_BASIC, target="netscape", **OPTS)["output"])

    def test_httponly_and_samesite(self):
        json_out = convert(NETSCAPE_HTTPONLY, **OPTS)["output"]
        self.assertTrue(json.loads(json_out)[0]["httpOnly"])
        self.assertIn("#HttpOnly_.example.com", convert(json_out, target="netscape", **OPTS)["output"])
        puppeteer = json.loads(convert(COOKIE_EDITOR, target="puppeteer", **OPTS)["output"])
        self.assertEqual(puppeteer[0]["sameSite"], "None")
        back = json.loads(convert(json.dumps(puppeteer), target="cookie-editor", **OPTS)["output"])
        self.assertEqual(back[0]["sameSite"], "no_restriction")

    def test_unspecified_samesite_omitted(self):
        netscape = f".example.com\tTRUE\t/\tFALSE\t{FUTURE}\tn\tv"
        out = json.loads(convert(netscape, target="puppeteer", **OPTS)["output"])
        self.assertNotIn("sameSite", out[0])

    def test_jwt_survives(self):
        raw = f".example.com\tTRUE\t/\tFALSE\t{FUTURE}\ttoken\t{JWT_VALUE}"
        for target in ("cookie-editor", "puppeteer", "key-value", "header"):
            self.assertIn(JWT_VALUE, convert(raw, target=target, **OPTS)["output"])

    def test_ms_expiry_round_trip(self):
        raw = json.dumps([{"name": "n", "value": "v", "domain": ".example.com", "expirationDate": FUTURE * 1000}])
        self.assertIn(f"\t{FUTURE}\t", convert(raw, target="netscape", **OPTS)["output"])

    def test_stats(self):
        raw = "\n".join(
            [
                f".example.com\tTRUE\t/\tFALSE\t{FUTURE}\ta\t1",
                f"example.com\tFALSE\t/\tTRUE\t{PAST}\tb\t2",
                ".other.com\tTRUE\t/\tFALSE\t0\tc\t3",
            ]
        )
        self.assertEqual(
            convert(raw, **OPTS)["stats"],
            {"total": 3, "domains": 2, "expired": 1, "session": 1, "secure": 1, "httpOnly": 0},
        )

    def test_errors_and_warnings(self):
        r = convert("the quick brown fox", **OPTS)
        self.assertFalse(r["ok"])
        self.assertEqual(r["issues"][0]["message"], "issue.unknownFormat")
        empty = convert("   ", **OPTS)
        self.assertFalse(empty["ok"])
        self.assertEqual(empty["issues"], [])
        huge = convert("x" * (MAX_INPUT_BYTES + 1), **OPTS)
        self.assertEqual(huge["issues"][0]["message"], "issue.tooLarge")
        dup = convert(
            "\n".join(
                [
                    f".example.com\tTRUE\t/\tFALSE\t{FUTURE}\tdup\tfirst",
                    f".example.com\tTRUE\t/\tFALSE\t{FUTURE}\tdup\tsecond",
                ]
            ),
            **OPTS,
        )
        self.assertEqual(len(dup["cookies"]), 1)
        self.assertEqual(dup["cookies"][0]["value"], "second")
        self.assertTrue(any(i["message"] == "issue.duplicates" for i in dup["issues"]))
        keep = convert(
            "\n".join(
                [
                    f".example.com\tTRUE\t/\tFALSE\t{FUTURE}\tsid\ta",
                    f".other.com\tTRUE\t/\tFALSE\t{FUTURE}\tsid\tb",
                    f".example.com\tTRUE\t/app\tFALSE\t{FUTURE}\tsid\tc",
                ]
            ),
            **OPTS,
        )
        self.assertEqual(len(keep["cookies"]), 3)
        self.assertTrue(
            any(i["message"] == "issue.missingDomain" for i in convert(HEADER, target="netscape", **OPTS)["issues"])
        )
        self.assertFalse(
            any(
                i["message"] == "issue.missingDomain"
                for i in convert(HEADER, target="netscape", default_domain="example.com", **OPTS)["issues"]
            )
        )
        for target in ("key-value", "header"):
            self.assertTrue(
                any(i["message"] == "issue.lossyTarget" for i in convert(NETSCAPE_BASIC, target=target, **OPTS)["issues"]),
                target,
            )
        collision = convert(
            "\n".join(
                [
                    ".example.com\tTRUE\t/\tFALSE\t0\tsid\ta",
                    ".other.com\tTRUE\t/\tFALSE\t0\tsid\tb",
                ]
            ),
            target="key-value",
            **OPTS,
        )
        self.assertTrue(any(i["message"] == "issue.nameCollision" for i in collision["issues"]))

    def test_output_shape(self):
        out = json.loads(convert(NETSCAPE_BASIC, **OPTS)["output"])
        self.assertEqual(
            list(out[0].keys()),
            [
                "domain",
                "expirationDate",
                "hostOnly",
                "httpOnly",
                "name",
                "path",
                "sameSite",
                "secure",
                "session",
                "storeId",
                "value",
            ],
        )
        temp = next(c for c in out if c["name"] == "temp")
        self.assertNotIn("expirationDate", temp)
        self.assertTrue(temp["session"])
        netscape = convert(COOKIE_EDITOR, **OPTS)["output"]
        self.assertTrue(netscape.endswith("\n"))
        line = next(l for l in netscape.split("\n") if "session_id" in l)
        self.assertEqual(len(line.split("\t")), 7)
        self.assertEqual(convert(KEY_VALUE, target="header", **OPTS)["output"], HEADER)

    def test_claude_market_dump(self):
        dump = "\n".join(
            [
                "# Netscape HTTP Cookie File",
                "# generated by claude-market validator",
                ".claude.ai\tTRUE\t/\tTRUE\t9999999999\t_fbp\tfb.1.1",
                '.claude.ai\tTRUE\t/\tTRUE\t9999999999\tg_state\t{"i_l":0,"i_e":{"x":1}}',
                ".claude.ai\tTRUE\t/\tTRUE\t9999999999\tsessionKey\tsk-ant-sid02-TEST",
                ".claude.ai\tTRUE\t/\tTRUE\t9999999999\tsessionKeyV3\tsk-ant-sid02-TEST",
            ]
        )
        for target in ALL_FORMATS:
            r = convert(dump, target=target, **OPTS)
            self.assertTrue(r["ok"], target)
            self.assertEqual(r["stats"]["total"], 4)
            self.assertIn("g_state", r["output"])
            self.assertIn("sessionKey", r["output"])
        results = convert_batch(join_cookie_sets([dump] * 10), target="cookie-editor", **OPTS)
        self.assertEqual(len(results), 10)
        self.assertTrue(all(r["ok"] and r["stats"]["total"] == 4 for r in results))


class SplitTests(unittest.TestCase):
    def test_empty_and_single(self):
        self.assertEqual(split_cookie_sets(""), [])
        self.assertEqual(len(split_cookie_sets(COOKIE_EDITOR)), 1)
        self.assertEqual(len(split_cookie_sets(NETSCAPE_BASIC)), 1)
        self.assertEqual(len(split_cookie_sets(HEADER)), 1)

    def test_json_concat(self):
        self.assertEqual(len(split_cookie_sets(f"{COOKIE_EDITOR}\n{COOKIE_EDITOR}")), 2)
        self.assertEqual(len(split_cookie_sets(f"{COOKIE_EDITOR}{PUPPETEER}")), 2)
        self.assertEqual(len(split_cookie_sets(f"{COOKIE_EDITOR}\n\n{PUPPETEER}\n\n{COOKIE_EDITOR}")), 3)

    def test_netscape_repeats(self):
        self.assertEqual(len(split_cookie_sets(f"{NETSCAPE_HTTPONLY}\n\n{NETSCAPE_BASIC}")), 2)
        self.assertEqual(
            len(split_cookie_sets(f"{NETSCAPE_NO_HEADER}\n{NETSCAPE_NO_HEADER}\n{NETSCAPE_NO_HEADER}")),
            3,
        )
        self.assertEqual(len(split_cookie_sets(f"{NETSCAPE_NO_HEADER}{NETSCAPE_NO_HEADER}")), 2)
        self.assertEqual(len(split_cookie_sets("\n\n".join([NETSCAPE_BASIC] * 3))), 3)

    def test_headers_and_mixed(self):
        self.assertEqual(len(split_cookie_sets(f"{HEADER}\n{HEADER}\n{HEADER}")), 3)
        self.assertEqual(len(split_cookie_sets(f"{NETSCAPE_NO_HEADER}\n\n{HEADER}")), 2)

    def test_cap(self):
        many = "\n".join([HEADER] * 50)
        self.assertEqual(len(split_cookie_sets(many)), MAX_SETS)

    def test_note_then_json(self):
        self.assertEqual(len(split_cookie_sets(f"two accounts\n{COOKIE_EDITOR}\n\n{PUPPETEER}")), 2)

    def test_json_looking_netscape_values(self):
        a = f'.example.com\tTRUE\t/\tFALSE\t{FUTURE}\tone\t{{"a":1}}'
        b = f'.example.com\tTRUE\t/\tFALSE\t{FUTURE}\ttwo\t{{"b":2}}'
        self.assertEqual(len(split_cookie_sets(f"{a}\n{b}")), 1)

    def test_batch_and_combined(self):
        results = convert_batch(f"{COOKIE_EDITOR}\n{PUPPETEER}", **OPTS)
        self.assertEqual(len(results), 2)
        self.assertTrue(all(r["ok"] for r in results))
        single = convert_batch(COOKIE_EDITOR, **OPTS)
        self.assertEqual(len(single), 1)
        combined = convert_combined(f"{COOKIE_EDITOR}\n{PUPPETEER}", **OPTS)
        self.assertTrue(combined["ok"])
        self.assertGreaterEqual(combined["stats"]["total"], 2)


if __name__ == "__main__":
    unittest.main()
