import type { Cookie } from '../types'

const HEADER = [
  '# Netscape HTTP Cookie File',
  '# https://curl.se/docs/http-cookies.html',
  '# Generated by claudecookie.com — this is a generated file, do not edit by hand.',
  '',
].join('\n')

/**
 * Writes a Netscape `cookies.txt` file: seven tab-separated fields per cookie.
 *
 * http-only cookies get curl's `#HttpOnly_` domain prefix, and session cookies
 * are written with an expiry of `0`, which is what every reader expects.
 */
export function serializeNetscape(cookies: Cookie[], includeHeader = true): string {
  const lines = cookies.map((c) => {
    const includeSubdomains = c.domain.startsWith('.') ? 'TRUE' : 'FALSE'
    const expires = c.session ? 0 : Math.round(c.expirationDate ?? 0)
    const domain = c.httpOnly ? `#HttpOnly_${c.domain}` : c.domain

    return [
      domain,
      includeSubdomains,
      c.path || '/',
      c.secure ? 'TRUE' : 'FALSE',
      String(expires),
      c.name,
      c.value,
    ].join('\t')
  })

  const body = lines.join('\n')
  return includeHeader ? `${HEADER}${body}\n` : `${body}\n`
}
